name: Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master' if your default branch is master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'  # Change if your HTML files are in a subfolder like 'dist' or 'build'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
